---

- name: install required packages
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: add percona repository
  apt:
    deb: "{{ percona_repository_package }}"

- name: update cache
  apt:
    update_cache: yes
  changed_when: false

- name: Check if percona datadir is present
  stat:
    path: "{{ percona_datadir }}"
  register: percona_datadir_check

- name: Recursively change permissions on percona datadir if needed
  file:
    path: "{{ percona_datadir }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '777'
  when: percona_datadir_check.stat.exists and percona_datadir_check.stat.pw_name != percona_user

- name: install packages
  apt:
    name:
      - "percona-xtradb-cluster-{{ percona_version }}"
      - "python3-pymysql"
      - "python3-mysqldb"
    state: present
