---

- name: install required packages
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: add percona repository
  apt:
    deb: "{{ percona_repository_package }}"

- name: update cache
  apt:
    update_cache: yes
  changed_when: false

- name: install packages
  apt:
    name:
      - "percona-xtradb-cluster-{{ percona_version }}"
      - "python-pymysql"
      - "python3-mysqldb"
    state: present
